### ISSUE TITLE
This fork is cringe.

### ISSUE THREAD

**Issue by mattkenefick** [dvoyakiy/youtube-dl-reborn#1]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.09.20**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dvoyakiy** [comment]
dude wtf

**Comment by mburszley** [comment]
GitHub has been responding to DMCA requests for much longer than Microsoft has ever been in a place to own them.

https://www.reddit.com/r/programming/comments/jib60n/youtubedl_and_the_streisand_effect/ga5id04/

**Comment by toolboc** [comment]
Why does the repo description say “fuck you microsoft”?  

The reason youtube-dl exists is because *YouTube* implements security through obscurity via minified JavaScript that is loaded on every YouTube video request whose sole purpose is to de-obfuscate the source content URLs for the content you are trying to view.  

Is it because Microsoft owns Github?  

You know, the Microsoft owned service that is currently hosting this source code which works around YouTube’s purposefully convoluted obfuscated source URLs?

The anger seems a bit misplaced here...
